// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqyyhmdporlzxbkxiqbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxeXlobWRwb3Jsenhia3hpcWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTM3MDQsImV4cCI6MjA3NDM4OTcwNH0.NaKg67VDUQdncYQVAfSPTNiQdKJLh5JtQKiwucL9v9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});